//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> qty { get; set; }
        public string cardno { get; set; }
        public string cvv { get; set; }
        public string exp_date { get; set; }
        public string name { get; set; }
        public string bookdate { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual user user { get; set; }
    }
}
